export const images={
    welcome_layout:require("../images/welcome_layout.png"),
    eye:require("../images/eye.png"),
    back:require("../images/back.png"),
    date_of_birth:require("../images/date_of_birth.png"),
    birth_time:require("../images/birth_time.png"),
    add_gender:require("../images/add_gender.png"),
    other:require("../images/other.png"),
    gender_female:require("../images/gender_female.png"),
    gender_male:require("../images/gender_male.png"),
    relationship_status:require("../images/relationship_status.png"),
    single:require("../images/single.png"),
    hand:require("../images/hand.png"),
    divorced:require("../images/divorced.png"),
    window:require("../images/window.png"),
    users:require("../images/users.png"),
    engaged:require("../images/engaged.png"),
    relationship:require("../images/relationship.png"),
    cancer:require("../images/cancer.png"),
    zodiac_cancer:require("../images/zodiac_cancer.png"),
    earth:require("../images/earth.png"),
    zodiac_leo:require("../images/zodiac_leo.png"),
    info_gender_female:require("../images/info_gender_female.png"),

    profile:require("../images/profile.png"),
    guidance:require("../images/guidance.png"),
    horoscope:require("../images/horoscope.png"),
    compatibility:require("../images/compatibility.png"),
    readings:require("../images/readings.png"),
    palm_reading:require("../images/palm_reading.png"),

    birth_chart_reading:require("../images/birth_chart_reading.png"),
    tarot_card_reading:require("../images/tarot_card_reading.png"),

    reading_detail:require("../images/reading_detail.png"),
    fingerprint:require("../images/fingerprint.png"),

    right_hand:require("../images/right_hand.png"),
    left_hand:require("../images/left_hand.png"),
    thumb:require("../images/thumb.png"),
    career:require("../images/career.png"),
    your_day:require("../images/your_day.png"),
    health:require("../images/health.png"),
    love:require("../images/love.png"),
    characteristics:require("../images/characteristics.png"),
    plus:require("../images/plus.png"),
    plus_primary:require("../images/plus_primary.png"),
    girl_cancer:require("../images/girl_cancer.png"),
    leo:require("../images/leo.png"),
    daily_tarot:require("../images/daily_tarot.png"),
    tarot_card:require("../images/tarot_card.png"),
    near_future:require("../images/near_future.png"),
    love_relations:require("../images/love_relations.png"),
    card_meanings:require("../images/card_meanings.png"),
    tarot_card_background:require("../images/tarot_card_background.png"),
    yes_or_no:require("../images/yes_or_no.png"),

    money_card:require("../images/money_card.png"),
    card_selection:require("../images/card_selection.png"),
    love_card:require("../images/love_card.png"),

    dollar:require("../images/dollar.png"),
    setting:require("../images/setting.png"),
    edit:require("../images/edit.png"),
    user:require("../images/user.png"),
    next:require("../images/next.png"),
    calendar:require("../images/calendar.png"),


    heart:require("../images/heart.png"),
    alert_square:require("../images/alert_square.png"),
    work:require("../images/work.png"),
    suggestions:require("../images/suggestions.png"),
    pisces:require("../images/pisces.png"),
    gemini:require("../images/gemini.png"),
    next_circle:require("../images/next_circle.png"),
    virgo:require("../images/virgo.png"),
    crose:require("../images/crose.png"),
    smile:require("../images/smile.png"),
    mode_off:require("../images/mode_off.png"),
    check_circle:require("../images/check_circle.png"),
    cross_circle:require("../images/cross_circle.png"),
    sagaittarius:require("../images/sagaittarius.png"),
    moon_step1:require("../images/moon_step1.png"),
    moon_step2:require("../images/moon_step2.png"),
    moon_step3:require("../images/moon_step3.png"),
    crystal_ball:require("../images/crystal_ball.png"),

    numerology:require("../images/numerology.png"),
    dream:require("../images/dream.png"),



    

    ball:require("../images/ball.png"),
    chat:require("../images/chat.png"),
    microphone:require("../images/microphone.png"),

    waxing_gibbous_moon1:require("../images/waxing_gibbous_moon1.png"),
    waxing_gibbous_moon:require("../images/waxing_gibbous_moon.png"),
    first_quarter_moon:require("../images/first_quarter_moon.png"),
    full_moon:require("../images/full_moon.png"),
    last_quarter_moon:require("../images/last_quarter_moon.png"),
    new_moon:require("../images/new_moon.png"),
    waxing_crescent_moon:require("../images/waxing_crescent_moon.png"),
    zodiac_aquarius:require("../images/zodiac_aquarius.png"),

    numerology_background:require("../images/numerology_background.png"),
    numerology_circle:require("../images/numerology_circle.png"),
    numerology_calendar:require("../images/numerology_calendar.png"),
    numerology_loading:require("../images/numerology_loading.png"),

    numerology_result_3:require("../images/numerology_result_3.png"),
    numerology_result_7:require("../images/numerology_result_7.png"),
    numerology_result_5:require("../images/numerology_result_5.png"),
    analysing_dream:require("../images/analysing_dream.png"),
    dream_revealed:require("../images/dream_revealed.png"),



    your_jupiter:require("../images/your_jupiter.png"),
    moon_square:require("../images/moon_square.png"),
    mars_sextile:require("../images/mars_sextile.png"),
    sun_time:require("../images/sun_time.png"),
    sun_trine_background:require("../images/sun_trine_background.png"),

    question:require("../images/question.png"),

    zodiac_virgo:require("../images/zodiac_virgo.png"),
    zodiac_capricorn:require("../images/zodiac_capricorn.png"),
    zodiac_libra:require("../images/zodiac_libra.png"),
    haumea:require("../images/haumea.png"),
    sun:require("../images/sun.png"),
    moon:require("../images/moon.png"),
    planer_earth:require("../images/planer_earth.png"),
    Jupiter:require("../images/Jupiter.png"),
    saturn:require("../images/saturn.png"),
    neptune:require("../images/neptune.png"),
    pluto:require("../images/pluto.png"),
    pluto_detail:require("../images/pluto_detail.png"),
    planet_sign:require("../images/planet_sign.png"),
    transits_detaill:require("../images/transits_detaill.png"),
    glow:require("../images/glow.png"),
    glow_bottom:require("../images/glow_bottom.png"),
    birth_chat:require("../images/birth_chat.png"),
    birth_transits_chart:require("../images/birth_transits_chart.png"),
    location_img:require("../images/location_img.png"),

    
    
    
    
}