export const URLS = {
  GOOGLE_MAP_KEY: "AIzaSyDxwAM_9axxJTDHas08AsXEXHhjHJTP71U",
  BASE_URL: "https://g3xhvfwyex.ap-south-1.awsapprunner.com",
  IMAGE_URL: "https://readings-storage.s3.ap-south-1.amazonaws.com",
  GOOGLE_PACES_API_BASE_URL: "https://maps.googleapis.com/maps/api/place",
  REGISTER: "/api/auth/register",
  LOGIN: "/api/auth/login",
  FORGOT_PASSWORD_EMAIL: "/api/auth/forget-password",
  CHANGE_PASSWORD: "/api/auth/change-password",
  HOME: "/api/home",
  BOOK_DETAIL: "/api/books",
  BOOK_REQUEST: "/api/request-a-book",
  BOOK_SEARCH: "/api/search",
  BOOK_BY_CATEGORY: "/api/category/level1",
  BOOK_BY_SUB_CATEGORY: "/api/category/level4",
  ADDRESSES: "/api/addresses",
  PROFILE: "/api/profile",
  DELETE_ACCOUNT: "/api/auth/delete-account",
  ADVANCE_SEARCH:"/api/searching-advance",
  High_DISCOUNT:"/api/high-discount-category/level1",
  WISHLIST:"/api/wishlist",
  HIGH_DISCOUNT_CATEGORIES:"/api/categories/high-discounts",
  Add_CART_ITEM:"/api/cart/add-item",
  GET_ORDER_CART:"/api/cart/order-cart",
  UPDATE_CART_ITEM:"/api/cart/update-cart-item",
  DELETE_CART_ITEM:"/api/cart/delete-cart-item"
};
